services:
  scylla:
    image: scylladb/scylla:latest
    volumes:
      - "./tests/docker/scylla:/var/lib/scylla"
    ports:
      - "8000:8000"
      - "9042:9042"
    command: "--smp 1 --alternator-port 8000 --alternator-write-isolation only_rmw_uses_lwt"

  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./tests/docker/s3:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
